# Generated by Django 3.0.3 on 2020-06-03 10:04

import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='hint',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='hint_question',
            field=models.IntegerField(default=1),
        ),
    ]
