# Generated by Django 3.0.3 on 2020-04-24 20:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('contents_for_plan', models.TextField()),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title_for_plan', models.CharField(blank=True, max_length=150)),
                ('contents_for_plan', models.TextField(blank=True)),
                ('title_for_result', models.CharField(blank=True, max_length=150)),
                ('contents_for_result', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('CONFIRM', 'Confirm'), ('COMPLETE', 'Complete'), ('SUCCESS', 'Success')], default='ENROLLMENT', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='groups.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=150)),
                ('file', models.FileField(null=True, upload_to='plan/file_for_result')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultfiles', to='plans.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=150)),
                ('file', models.FileField(null=True, upload_to='plan/file_for_plan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planfiles', to='plans.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
