# Generated by Django 3.0.3 on 2020-03-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('contents_for_plan', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('contents_for_plan', models.CharField(max_length=2000)),
                ('file_for_plan', models.FileField(null=True, upload_to='')),
                ('contents_for_result', models.CharField(max_length=2000)),
                ('file_for_result', models.FileField(null=True, upload_to='')),
                ('start_day', models.DateField(blank=True, null=True)),
                ('end_day', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('CONFIRM', 'Confirm'), ('COMPLETE', 'Complete'), ('FAIL', 'Fail'), ('SUCCESS', 'Success')], default='ENROLLMENT', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
