# Generated by Django 3.0.3 on 2020-04-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20200421_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
