# Generated by Django 3.0.3 on 2020-03-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20200310_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contents_for_plan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='contents_for_plan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='contents_for_result',
            field=models.TextField(),
        ),
    ]
