# Generated by Django 3.0.3 on 2020-03-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20200311_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='title',
        ),
        migrations.AddField(
            model_name='plan',
            name='title_for_plan',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='plan',
            name='title_for_result',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='contents_for_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='contents_for_result',
            field=models.TextField(blank=True),
        ),
    ]
