# Generated by Django 3.0.3 on 2020-04-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20200416_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('CONFIRM', 'Confirm'), ('COMPLETE', 'Complete'), ('SUCCESS', 'Success')], default='ENROLLMENT', max_length=20),
        ),
    ]
