# Generated by Django 3.0.3 on 2020-03-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20200311_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='file_for_plan',
            field=models.FileField(null=True, upload_to='uploads/plan/file_for_plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='file_for_result',
            field=models.FileField(null=True, upload_to='uploads/plan/file_for_result'),
        ),
    ]
