# Generated by Django 3.0.3 on 2020-03-11 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20200311_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='file_for_plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='file_for_result',
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=150)),
                ('file', models.FileField(null=True, upload_to='uploads/plan/file_for_result')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=150)),
                ('file', models.FileField(null=True, upload_to='uploads/plan/file_for_plan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
