# Generated by Django 3.0.3 on 2020-04-24 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('S', 'Study'), ('R', 'Reading'), ('E', 'Exercise'), ('H', 'Hobby')], default='S', max_length=2)),
                ('title', models.CharField(max_length=150)),
                ('notice', models.TextField()),
                ('contents', models.TextField()),
                ('max_group_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('planning_unit', models.CharField(choices=[('week', 'Week'), ('day', 'Day')], default='week', max_length=10)),
                ('deadline_week', models.CharField(choices=[('MON', '월요일'), ('TUE', '화요일'), ('WHE', '수요일'), ('THU', '목요일'), ('FRI', '금요일'), ('SAT', '토요일'), ('SUN', '일요일')], default='MON', max_length=5)),
                ('deadline_day', models.CharField(choices=[('0', '0 시'), ('1', '1 시'), ('2', '2 시'), ('3', '3 시'), ('4', '4 시'), ('5', '5 시'), ('6', '6 시'), ('7', '7 시'), ('8', '8 시'), ('9', '9 시'), ('10', '10 시'), ('11', '11 시'), ('12', '12 시'), ('13', '13 시'), ('14', '14 시'), ('15', '15 시'), ('16', '16 시'), ('17', '17 시'), ('18', '18 시'), ('19', '19 시'), ('20', '20 시'), ('21', '21 시'), ('22', '22 시'), ('23', '23 시')], default=0, max_length=2)),
                ('photo', models.ImageField(blank=True, upload_to='group/group_photo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
