# Generated by Django 3.0.3 on 2020-04-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200417_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/group/group_photo'),
        ),
    ]
