# Generated by Django 3.0.3 on 2020-03-11 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contents',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='notice',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
