# Generated by Django 3.0.3 on 2020-04-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, upload_to='group/group_photo'),
        ),
    ]
