# Generated by Django 3.0.3 on 2020-03-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200311_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='notice',
            field=models.TextField(),
        ),
    ]
