# Generated by Django 3.0.3 on 2020-03-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20200311_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupId',
        ),
    ]
